#name: Pull Request testing

on:
  pull_request:
    types: [opened, reopened, review_requested, edited, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
              ~/.cache/pip
              ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build X10A definitions
        run: python3 scripts/build_x10a_commands.py

      - name: Build CAN definitions
        run: python3 scripts/build_can_commands.py

      - name: Run Unit Tests
        run: pio test -e native

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32, esp32_debug_noBT, nodemcuv2, m5stickc, m5stack-tough, m5stickcplus, m5stickcplus2]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
              ~/.cache/pip
              ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e ${{ matrix.target }}

      - name: Create build folder
        run: mkdir -p build

      - name: Check if binary successfully created
        run: test .pio/build/${{ matrix.target }}/firmware.bin